### ISSUE TITLE
Can we set cmake_minimum_required to 3.10?

### ISSUE THREAD

**Issue by astumpf** [ethz-asl/tracy_catkin#1]
In Ubuntu 18.04, the last shipped version that uses the official Debian package sources is 3.10, so it would be very handy to reduce the required version and allow users who are sticking with Ubuntu 18.04 for some reason to use that and any dependent packages like wavemap. I couldn't find any changes in 3.11 that might be relevant here.

**Comment by victorreijgwart** [comment]
Thanks for pointing this out. The minimum CMake version requirement for `3.11` is a leftover from initial packaging attempts using FetchContent. But since using ExternalProject ended up working better, we no longer need it. I pushed a new commit that lowers the required version to `3.0.2` to make it consistent with wavemap.
Hopefully, this solves the issue. If not, don't hesitate to reopen it.

**Comment by astumpf** [comment]
Thanks a lot!
